server:
  servlet:
    encoding:
      force-response: true

    session:
      tracking-modes: cookie
      timeout: 1800

spring:
  messages:
      basename: "messages,errors"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true